services:
  - type: web
    name: universal-media-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here-change-this-in-production
